### ISSUE TITLE
Can you offer the detail to rerun the work?

### ISSUE THREAD

**Issue by sja9527** [BoPang1996/PGT#1]
Thanks your great job! Can you offer the detail to rerun the work? I don't know how to run the model.

**Comment by ecr23xx** [comment]
Please refer to [GETTING_STARTED.md](https://github.com/facebookresearch/SlowFast/blob/main/GETTING_STARTED.md) from facebookresearch/SlowFast, which our work is built on.

请参考 facebookresearch/SlowFast 的 [GETTING_STARTED.md](https://github.com/facebookresearch/SlowFast/blob/main/GETTING_STARTED.md)。我们的工作基于这个仓库开发，程序运行方式一样。
